# Generated by Django 4.2.6 on 2023-11-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="post",
            new_name="posts",
        ),
    ]
